// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY']!,
    appId: '1:36165165084:web:f3c2d7e9cce6f41b2a7fd9',
    messagingSenderId: '36165165084',
    projectId: 'soulswaroop-2b309',
    authDomain: 'soulswaroop-2b309.firebaseapp.com',
    storageBucket: 'soulswaroop-2b309.firebasestorage.app',
    measurementId: 'G-QC46G9LQRQ',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY']!,
    appId: '1:36165165084:android:5bd1c67470a7801b2a7fd9',
    messagingSenderId: '36165165084',
    projectId: 'soulswaroop-2b309',
    storageBucket: 'soulswaroop-2b309.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY']!,
    appId: '1:36165165084:ios:d880dec2cfedbe6c2a7fd9',
    messagingSenderId: '36165165084',
    projectId: 'soulswaroop-2b309',
    storageBucket: 'soulswaroop-2b309.firebasestorage.app',
    iosBundleId: 'com.example.soulswaroop',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY']!,
    appId: '1:36165165084:ios:d880dec2cfedbe6c2a7fd9',
    messagingSenderId: '36165165084',
    projectId: 'soulswaroop-2b309',
    storageBucket: 'soulswaroop-2b309.firebasestorage.app',
    iosBundleId: 'com.example.soulswaroop',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY']!,
    appId: '1:36165165084:web:8aeba2b2214377fb2a7fd9',
    messagingSenderId: '36165165084',
    projectId: 'soulswaroop-2b309',
    authDomain: 'soulswaroop-2b309.firebaseapp.com',
    storageBucket: 'soulswaroop-2b309.firebasestorage.app',
    measurementId: 'G-DF0HY72Z87',
  );

}